### ISSUE TITLE
Tech evaluation: adding custom names to containers/inventories?

### ISSUE THREAD

**Issue by DonnEssime** [DonnEssime/Custom-Salem#41]
Is this possible? I would have to do an evaluation of the persistence of gob ids over sessions/server restarts.

**Comment by LOMS** [comment]
Not sure. Back to old Haven & Hearth, I've heard about the problems with gob ids, like, they are similar between sessions and players, but they are not persistent between sessions, thus you can't rely on plain gob IDs when you make a detailed map or a bot. I never checked this in Salem though.
For your testing you may do the following:
Pick a certain chunk of your own base.
Make file with all brickwall segments (or other wall) coordinates and IDs (you should alter your client, yeah).
Wait for restart and do that again.
Compare results.

In Salem, you always have a lot of walls, and they are persistent enough to rely on, thus this will be a good test. 
Otherwise, you can be lazy and do the thing with single object id, like mine entrance. This is not as good as wall test, because it's possible that some object do change their public IDs between restart, and some objects not.

**Comment by DonnEssime** [comment]
yeah, that's how I will be doing it, this was mainly just a reminder for myself :-) 
I know the gobids are persistent between players, i.e. everyone sees the same gobids (otherwise the highlight function from ender would not be working) - but I am unsure whether gobids are persistent over server restarts.

**Comment by DonnEssime** [comment]
Tested this once more, gob ids get reset when the tile is unloaded from server memory. Unfeasible.
