### ISSUE TITLE
Ctrl+A and weight

### ISSUE THREAD

**Issue by Nsuidara** [DonnEssime/Custom-Salem#42]
is possible add weight ? near amounts/count items ?

**Comment by DonnEssime** [comment]
unfortunately, not easily.
The client has no idea about the weight of the individual items. It only receives the total weight of the inventory from the server.

There are two options if I would want to add this:
- Nag with JC long enough so that the items also send their weight as part of their ItemInfo (which is used to build the tooltip)
- Build a database of object weights, and parse it for the various items and their weight. This is probably the most feasible of the two, but I don't look forward to doing it.

Thinking of it, I could probably write a small bit of code that would periodically save item inventories and their total weight to file. With a bit of parsing/smart programming I should be able to figure out item weights from that. Will investigate (should have a bit of time for client programming soon!).

**Comment by LOMS** [comment]
You can't do that, since there are containers with dynamic weight in your inventory.

**Comment by DonnEssime** [comment]
You are right, of course. I thought about the vegetable sacks and the like just now, so those will will make the earlier idea impossible. 

The only possible option is "annoy JC about it"

**Comment by Nsuidara** [comment]
but cant
got weight before pickup item ? 
amd wjem picked weight

new_weight - old_weight = item_weight ?

**Comment by DonnEssime** [comment]
as LOMS pointed out, some items don't have a set weight.
Also, the split second an item enters the inventory, it is actually a "null" object without any information until the server sends the item info. The weight is also not necessarily updated before or after the item enters the inventory.
