### ISSUE TITLE
Well and autopick ? 

### ISSUE THREAD

**Issue by Nsuidara** [DonnEssime/Custom-Salem#46]
is possible add auto-bucked in well ?

mean when i click one bucked vs well... they full all bucked in inventory ?

**Comment by LOMS** [comment]
Well you look at that, someone finally spoke about a bot *trollface*
Actually, I had this feature in my private client, without any botting. I also had shift-planting for pots before John assigned them to "shiftable" group on server. Here's my approach:
Just catch a moment when DragItem is destroyed, created or changed (like buckets, DragItem's object remains the same after content of dragged bucket changing), then take new item from inventory or swap your current DragItem with desired item from your inventory.
I called that "Smart Shift" and used simple shift key for it. His "Smartness" was toggleable so I had no conflict with normal "Shiftable" objects, like pot plants, humus, fuel etc.

Despite apparent simplicity, implementation could be a bit tricky, because you need to parse your inventories, making this "Smart Shift" toggleable or something, etc etc. My implementation also had a HUGE conflict with inventory sorting, but I was too lazy to fix that.

**Comment by DonnEssime** [comment]
I have implemented something similar with the autobucket feature: whenever you're standing over water, and an empty bucket pops up in your hand, it will right click the location you are standing on, effectively filling the bucket. As rivers are so much faster than wells, I won't be including a well feature until more people ask for this.
