### ISSUE TITLE
Picking up multiple items at the same time

### ISSUE THREAD

**Issue by DonnEssime** [DonnEssime/Custom-Salem#55]
Does the server allow picking up multiple items simultaneously?

**Comment by LOMS** [comment]
What do you mean? Picking items from the ground, or picking a bunch of items under cursor?
You can't pick multiple items from the ground at the time, because you need to interact with each instance of item one by one.

Regarding cursor, I've heard there were several exploits (both in Haven and Salem), that allowed you to pick multiple items with cursor. I don't know details, but I believe Loftar fixed all of them.

**Comment by DonnEssime** [comment]
The question was actually more of a reminder to myself - I was wondering whether I could generate multiple wdgmsg's at the same time and send them to the server in batch. Turns out you can't, the server will only act on a single one of them.
